"""empty message

Revision ID: c055e53cb57e
Revises: 
Create Date: 2023-12-05 11:58:43.767598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c055e53cb57e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skan_mock_app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('srn', sa.String(), nullable=False),
    sa.Column('app_configuration', sa.JSON(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skan_mock_google_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_path', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skan_mock_google_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('network_user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skan_mock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srn', sa.String(), nullable=False),
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skan_mock_history')
    op.drop_table('skan_mock_google_tokens')
    op.drop_table('skan_mock_google_config')
    op.drop_table('skan_mock_app_config')
    # ### end Alembic commands ###
